//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidadorXML.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfc_lista_negra
    {
        public int Id { get; set; }
        public string rfc { get; set; }
        public string nombre { get; set; }
    }
}
